/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as LighthousesRouteImport } from './routes/lighthouses'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlacesPuertoWilliamsRouteImport } from './routes/places/puerto-williams'

const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const LighthousesRoute = LighthousesRouteImport.update({
  id: '/lighthouses',
  path: '/lighthouses',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesPuertoWilliamsRoute = PlacesPuertoWilliamsRouteImport.update({
  id: '/puerto-williams',
  path: '/puerto-williams',
  getParentRoute: () => PlacesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas': typeof AtlasRoute
  '/lighthouses': typeof LighthousesRoute
  '/places': typeof PlacesRouteWithChildren
  '/routes': typeof RoutesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/travel': typeof TravelRoute
  '/places/puerto-williams': typeof PlacesPuertoWilliamsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas': typeof AtlasRoute
  '/lighthouses': typeof LighthousesRoute
  '/places': typeof PlacesRouteWithChildren
  '/routes': typeof RoutesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/travel': typeof TravelRoute
  '/places/puerto-williams': typeof PlacesPuertoWilliamsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas': typeof AtlasRoute
  '/lighthouses': typeof LighthousesRoute
  '/places': typeof PlacesRouteWithChildren
  '/routes': typeof RoutesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/travel': typeof TravelRoute
  '/places/puerto-williams': typeof PlacesPuertoWilliamsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/atlas'
    | '/lighthouses'
    | '/places'
    | '/routes'
    | '/sitemap.xml'
    | '/travel'
    | '/places/puerto-williams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/atlas'
    | '/lighthouses'
    | '/places'
    | '/routes'
    | '/sitemap.xml'
    | '/travel'
    | '/places/puerto-williams'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/atlas'
    | '/lighthouses'
    | '/places'
    | '/routes'
    | '/sitemap.xml'
    | '/travel'
    | '/places/puerto-williams'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AtlasRoute: typeof AtlasRoute
  LighthousesRoute: typeof LighthousesRoute
  PlacesRoute: typeof PlacesRouteWithChildren
  RoutesRoute: typeof RoutesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TravelRoute: typeof TravelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lighthouses': {
      id: '/lighthouses'
      path: '/lighthouses'
      fullPath: '/lighthouses'
      preLoaderRoute: typeof LighthousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/puerto-williams': {
      id: '/places/puerto-williams'
      path: '/puerto-williams'
      fullPath: '/places/puerto-williams'
      preLoaderRoute: typeof PlacesPuertoWilliamsRouteImport
      parentRoute: typeof PlacesRoute
    }
  }
}

interface PlacesRouteChildren {
  PlacesPuertoWilliamsRoute: typeof PlacesPuertoWilliamsRoute
}

const PlacesRouteChildren: PlacesRouteChildren = {
  PlacesPuertoWilliamsRoute: PlacesPuertoWilliamsRoute,
}

const PlacesRouteWithChildren =
  PlacesRoute._addFileChildren(PlacesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AtlasRoute: AtlasRoute,
  LighthousesRoute: LighthousesRoute,
  PlacesRoute: PlacesRouteWithChildren,
  RoutesRoute: RoutesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TravelRoute: TravelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
